name: mind_ui
description: Shared UI components and theming for Mind app.
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: any
  mind_l10n:
    path: ../mind_l10n
